# Generated by Django 3.2.25 on 2024-04-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quienvaganando', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apodo',
        ),
    ]
