# Generated by Django 3.2.25 on 2024-05-03 20:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quienvaganando', '0002_remove_user_apodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
