# Generated by Django 3.2.25 on 2024-06-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quienvaganando', '0004_alter_torneo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='campo_extra_a',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='partido',
            name='campo_extra_b',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='partido',
            name='categoria',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='partido',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='lugar',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='partido',
            name='resultado_a',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='partido',
            name='resultado_b',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='torneo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
