# Generated by Django 3.2.25 on 2024-07-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quienvaganando', '0005_auto_20240629_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='resultado_a',
            field=models.CharField(blank=True, default='TBD', max_length=250),
        ),
        migrations.AlterField(
            model_name='partido',
            name='resultado_b',
            field=models.CharField(blank=True, default='TBD', max_length=250),
        ),
    ]
